# Generated by Django 5.2.6 on 2025-10-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_clientes', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='cliente', max_length=255)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('data_inclusao', models.DateTimeField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concessionaria',
            fields=[
                ('id_concessionarias', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='concessionaria', max_length=255)),
            ],
            options={
                'db_table': 'concessionarias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id_veiculos', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inclusao', models.DateTimeField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'veiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_vendas', models.IntegerField(primary_key=True, serialize=False)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_venda', models.DateTimeField()),
                ('data_inclusao', models.DateTimeField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id_vendedores', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_inclusao', models.DateTimeField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendedores',
                'managed': False,
            },
        ),
    ]
